source :rubygems

gem 'rake'
gem 'rack', '1.3.6'
gem 'rack-contrib'
gem 'erubis'
gem 'rdiscount'
gem 'tilt'
gem 'http_router'
gem 'thin'
gem 'yarf', :git => 'git://github.com/zh/yarf.git'

group :test do
  gem 'rack-test'
  gem 'rspec'
end
